spring:
  application:
    name: task-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/rock_paper_scissors}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false


server:
  port: 8080
